export const cadencesData = [
  {
    cadence_name: 'ABC',
    steps: 3,
    owner: 'yuvraj',
    type: 'inbound',
    language: 'english',
  },
  {
    cadence_name: 'ABC',
    steps: 6,
    owner: 'yuvraj',
    type: 'inbound',
    language: 'english',
  },
  {
    cadence_name: 'ABC',
    steps: 7,
    owner: 'yuvraj',
    type: 'inbound',
    language: 'english',
  },
  {
    cadence_name: 'ABC',
    steps: 3,
    owner: 'yuvraj',
    type: 'inbound',
    language: 'english',
  },
  {
    cadence_name: 'ABC2',
    steps: 13,
    owner: 'yuvraj',
    type: 'inbound',
    language: 'english',
  },
  {
    cadence_name: 'ABC',
    steps: 3,
    owner: 'yuvraj',
    type: 'outbound',
    language: 'spanish',
  },
  {
    cadence_name: 'ABC1',
    steps: 9,
    owner: 'yuvraj',
    type: 'inbound',
    language: 'french',
  },
  {
    cadence_name: 'ABC',
    steps: 3,
    owner: 'UV',
    type: 'inbound',
    language: 'spanish',
  },
  {
    cadence_name: 'ABC',
    steps: 8,
    owner: 'yuvraj1',
    type: 'outbound',
    language: 'french',
  },
];
