export const VIEWS = {
  LEAD: 'lead',
  CONTACT: 'contact',
  ACCOUNT: 'account',
  CUSTOM_OBJECTS: 'custom_objects',
};
export const CUSTOM_OBJECT = {
  [VIEWS.LEAD]: [],
  [VIEWS.CONTACT]: [],
};

//hovers are the uids from 3types of below constants
export const QUICKVIEW_FIELDS = {
  INTEGRATION_STATUS: {
    value: 'qvf_integration_status',
    hovers: ['__integration_status'],
    hoversFor: [VIEWS.LEAD, VIEWS.ACCOUNT],
  },
  LINKEDIN_URL: {
    value: 'qvf_linkedin_url',
    hovers: ['__linkedin_url'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  COMPANY_URL: {
    value: 'qvf_company_url',
    hovers: ['__company_url'],
    hoversFor: [VIEWS.ACCOUNT, VIEWS.LEAD],
  },
  // ZOOM_INFO: {
  // 	value: "qvf_zoom_info",
  // 	hovers: ["__zoom_info"],
  // 	hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  // },
  FIRST_NAME: {
    value: 'qvf_first_name',
    hovers: ['__first_name'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  LAST_NAME: {
    value: 'qvf_last_name',
    hovers: ['__last_name'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  JOB_POSITION: {
    value: 'qvf_job_position',
    hovers: ['__job_position'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  COMPANY_NAME: {
    value: 'qvf_company_name',
    hovers: ['__lead_company_name', '__company_name'],
    hoversFor: [VIEWS.ACCOUNT, VIEWS.LEAD],
  },
  COMPANY_SIZE: {
    value: 'qvf_company_size',
    hovers: ['__company_size'],
    hoversFor: [VIEWS.ACCOUNT, VIEWS.LEAD],
  },
  COMPANY_PHONE_NUMBER: {
    value: 'qvf_company_phone_number',
    hovers: ['__company_phone_number'],
    hoversFor: [VIEWS.ACCOUNT],
  },
  ZIPCODE: {
    value: 'qvf_zipcode',
    hovers: ['__zipcode'],
    hoversFor: [VIEWS.ACCOUNT, VIEWS.LEAD],
  },
  COUNTRY: {
    value: 'qvf_country',
    hovers: ['__country'],
    hoversFor: [VIEWS.ACCOUNT, VIEWS.LEAD],
  },
  P_EMAIL: {
    value: 'qvf_p_email',
    hovers: ['__p_email'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  A_EMAIL1: {
    value: 'qvf_a_email1',
    hovers: ['__a_email1'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  A_EMAIL2: {
    value: 'qvf_a_email2',
    hovers: ['__a_email2'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  A_EMAIL3: {
    value: 'qvf_a_email3',
    hovers: ['__a_email3'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  A_EMAIL4: {
    value: 'qvf_a_email4',
    hovers: ['__a_email4'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  P_PHONE_NUMBER: {
    value: 'qvf_p_phone_number',
    hovers: ['__p_phone_number'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  A_PHONE_NUMBER1: {
    value: 'qvf_a_phone_number1',
    hovers: ['__a_phone_number1'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  A_PHONE_NUMBER2: {
    value: 'qvf_a_phone_number2',
    hovers: ['__a_phone_number2'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  A_PHONE_NUMBER3: {
    value: 'qvf_a_phone_number3',
    hovers: ['__a_phone_number3'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
  A_PHONE_NUMBER4: {
    value: 'qvf_a_phone_number4',
    hovers: ['__a_phone_number4'],
    hoversFor: [VIEWS.LEAD, VIEWS.CONTACT],
  },
};

//parseValues are used for implementing final construction of object before sending
//hovers is used to hover in quickView

const LEAD_FIELDS = [
  {
    uid: '__first_name',
    label: 'First Name',
    value: { name: '' },
    backendField: 'first_name',
    hovers: [QUICKVIEW_FIELDS.FIRST_NAME.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__last_name',
    label: 'Last Name',
    value: { name: '' },
    backendField: 'last_name',
    hovers: [QUICKVIEW_FIELDS.LAST_NAME.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__linkedin_url',
    label: 'Linkedin URL',
    value: { name: '' },
    backendField: 'linkedin_url',
    hovers: [QUICKVIEW_FIELDS.LINKEDIN_URL.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__job_position',
    label: 'Job position',
    value: { name: '' },
    backendField: 'job_position',
    hovers: [QUICKVIEW_FIELDS.JOB_POSITION.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__lead_company_name',
    label: 'Company Name',
    value: { name: '' },
    backendField: 'company',
    hovers: [QUICKVIEW_FIELDS.COMPANY_NAME.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__company_size',
    label: 'Company Size',
    value: { name: '' },
    backendField: 'size',
    hovers: [QUICKVIEW_FIELDS.COMPANY_SIZE.value],
    isArray: false,
    type: ['string', 'picklist'],
  },
  {
    uid: '__company_url',
    label: 'Company URL',
    value: { name: '' },
    backendField: 'url',
    hovers: [QUICKVIEW_FIELDS.COMPANY_URL.value],
    type: ['string'],
    isArray: false,
  },
  {
    uid: '__zipcode',
    label: 'Zipcode',
    value: { name: '' },
    backendField: 'zip_code',
    hovers: [QUICKVIEW_FIELDS.ZIPCODE.value],
    type: ['string'],
    isArray: false,
  },
  {
    uid: '__country',
    label: 'Country',
    value: { name: '' },
    backendField: 'country',
    hovers: [QUICKVIEW_FIELDS.COUNTRY.value],
    type: ['string'],
    isArray: false,
  },
  // {
  // 	uid: "__zoom_info",
  // 	label: "Zoom Info",
  // 	value: { name: "" },
  // 	backendField: "zoom_info",
  // 	hovers: [QUICKVIEW_FIELDS.ZOOM_INFO.value],
  // 	type: ["string"],
  // 	isArray: false,
  // },
  {
    uid: '__p_phone_number',
    label: 'Primary Phone Number',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.P_PHONE_NUMBER.value],
    isArray: true,
    type: ['string'],
    index: 0,
  },
  {
    uid: '__a_phone_number1',
    label: 'Mobile Phone',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.A_PHONE_NUMBER1.value],
    isArray: true,
    type: ['string'],
    index: 1,
  },
  {
    uid: '__a_phone_number2',
    label: 'Company Phone',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.A_PHONE_NUMBER2.value],
    isArray: true,
    type: ['string'],
    index: 2,
  },
  {
    uid: '__a_phone_number3',
    label: 'Other Phone 1',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.A_PHONE_NUMBER3.value],
    isArray: true,
    type: ['string'],
    index: 3,
  },
  {
    uid: '__a_phone_number4',
    label: 'Other Phone 2',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.A_PHONE_NUMBER4.value],
    isArray: true,
    type: ['string'],
    index: 4,
  },
  {
    uid: '__p_email',
    label: 'Primary Email',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.P_EMAIL.value],
    isArray: true,
    type: ['string'],
    index: 0,
  },
  {
    uid: '__a_email1',
    label: 'Alternative Email 1',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.A_EMAIL1.value],
    isArray: true,
    index: 1,
    type: ['string'],
  },
  {
    uid: '__a_email2',
    label: 'Alternative Email 2',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.A_EMAIL2.value],
    isArray: true,
    index: 2,
    type: ['string'],
  },
  {
    uid: '__a_email3',
    label: 'Alternative Email 3',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.A_EMAIL3.value],
    isArray: true,
    index: 3,
    type: ['string'],
  },
  {
    uid: '__a_email4',
    label: 'Alternative Email 4',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.A_EMAIL4.value],
    isArray: true,
    index: 4,
    type: ['string'],
  },
  // {
  // 	uid: "__integration_status",
  // 	label: "Integration Status",
  // 	value: {
  // 		name: "",
  // 	},
  // 	backendField: "integration_status",
  // 	hovers: [QUICKVIEW_FIELDS.INTEGRATION_STATUS.value],
  // 	isArray: false,
  // 	type: ["picklist"],
  // },
  // {
  // 	uid: "__disqualification_reasons",
  // 	label: "Disqualify Reasons",
  // 	picklist_values: [],
  // 	value: { name: "DisqualificationReason", picklist_values: [] },
  // 	backendField: "disqualification_reason",
  // 	hovers: [],
  // 	isArray: false,
  // 	type: ["picklist"],
  // },
  // {
  // 	uid: "__variable1",
  // 	label: "Variable 1",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 0,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable2",
  // 	label: "Variable 2",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 1,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable3",
  // 	label: "Variable 3",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 2,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable4",
  // 	label: "Variable 4",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 3,
  // 	type: ["string"],
  // },
];

const CONTACT_FIELDS = [
  {
    uid: '__first_name',
    label: 'First Name',
    value: { name: '' },
    backendField: 'first_name',
    hovers: [QUICKVIEW_FIELDS.FIRST_NAME.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__last_name',
    label: 'Last Name',
    value: { name: '' },
    backendField: 'last_name',
    hovers: [QUICKVIEW_FIELDS.LAST_NAME.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__linkedin_url',
    label: 'Linkedin URL',
    value: { name: '' },
    backendField: 'linkedin_url',
    hovers: [QUICKVIEW_FIELDS.LINKEDIN_URL.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__job_position',
    label: 'Job position',
    value: { name: '' },
    backendField: 'job_position',
    hovers: [QUICKVIEW_FIELDS.JOB_POSITION.value],
    isArray: false,
    type: ['string'],
  },
  // {
  // 	uid: "__zoom_info",
  // 	label: "Zoom Info",
  // 	value: { name: "" },
  // 	backendField: "zoom_info",
  // 	hovers: [QUICKVIEW_FIELDS.ZOOM_INFO.value],
  // 	type: ["string"],
  // 	isArray: false,
  // },
  {
    uid: '__p_phone_number',
    label: 'Primary Phone Number',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.P_PHONE_NUMBER.value],
    isArray: true,
    index: 0,
    type: ['string'],
  },
  {
    uid: '__a_phone_number1',
    label: 'Mobile Phone',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.A_PHONE_NUMBER1.value],
    isArray: true,
    index: 1,
    type: ['string'],
  },
  {
    uid: '__a_phone_number2',
    label: 'Other Phone 1',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.A_PHONE_NUMBER2.value],
    isArray: true,
    index: 2,
    type: ['string'],
  },
  {
    uid: '__a_phone_number3',
    label: 'Other Phone 2',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.A_PHONE_NUMBER3.value],
    isArray: true,
    index: 3,
    type: ['string'],
  },
  {
    uid: '__a_phone_number4',
    label: 'Other Phone 3',
    value: { name: '' },
    backendField: 'phone_numbers',
    hovers: [QUICKVIEW_FIELDS.A_PHONE_NUMBER4.value],
    isArray: true,
    index: 4,
    type: ['string'],
  },
  {
    uid: '__p_email',
    label: 'Primary Email',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.P_EMAIL.value],
    isArray: true,
    index: 0,
    type: ['string'],
  },
  {
    uid: '__a_email1',
    label: 'Alternative Email 1',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.A_EMAIL1.value],
    isArray: true,
    index: 1,
    type: ['string'],
  },
  {
    uid: '__a_email2',
    label: 'Alternative Email 2',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.A_EMAIL2.value],
    isArray: true,
    index: 2,
    type: ['string'],
  },
  {
    uid: '__a_email3',
    label: 'Alternative Email 3',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.A_EMAIL3.value],
    isArray: true,
    index: 3,
    type: ['string'],
  },
  {
    uid: '__a_email4',
    label: 'Alternative Email 4',
    value: { name: '' },
    backendField: 'emails',
    hovers: [QUICKVIEW_FIELDS.A_EMAIL4.value],
    isArray: true,
    index: 4,
    type: ['string'],
  },
  // {
  // 	uid: "__variable1",
  // 	label: "Variable 1",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 0,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable2",
  // 	label: "Variable 2",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 1,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable3",
  // 	label: "Variable 3",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 2,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable4",
  // 	label: "Variable 4",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 3,
  // 	type: ["string"],
  // },
];

const ACCOUNT_FIELDS = [
  {
    uid: '__company_name',
    label: 'Company Name',
    value: { name: '' },
    backendField: 'name',
    hovers: [QUICKVIEW_FIELDS.COMPANY_NAME.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__company_phone_number',
    label: 'Company Phone Number',
    value: { name: '' },
    backendField: 'phone_number',
    hovers: [QUICKVIEW_FIELDS.COMPANY_PHONE_NUMBER.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__company_size',
    label: 'Company Size',
    value: { name: '' },
    backendField: 'size',
    hovers: [QUICKVIEW_FIELDS.COMPANY_SIZE.value],
    isArray: false,
    type: ['string', 'picklist'],
  },
  {
    uid: '__company_url',
    label: 'Company URL',
    value: { name: '' },
    backendField: 'url',
    hovers: [QUICKVIEW_FIELDS.COMPANY_URL.value],
    isArray: false,
    type: ['string'],
  },
  {
    uid: '__zipcode',
    label: 'Zipcode',
    value: { name: '' },
    backendField: 'zip_code',
    hovers: [QUICKVIEW_FIELDS.ZIPCODE.value],
    type: ['string'],
    isArray: false,
  },
  {
    uid: '__country',
    label: 'Country',
    value: { name: '' },
    backendField: 'country',
    hovers: [QUICKVIEW_FIELDS.COUNTRY.value],
    type: ['string'],
    isArray: false,
  },
  // {
  // 	uid: "__integration_status",
  // 	label: "Integration Status",
  // 	value: {
  // 		name: "",
  // 		picklist_values: [],
  // 		converted: {},
  // 		disqualified: {},
  // 	},
  // 	backendField: "integration_status",
  // 	hovers: [QUICKVIEW_FIELDS.INTEGRATION_STATUS.value],
  // 	isArray: false,
  // 	type: ["picklist"],
  // },
  // {
  // 	uid: "__disqualification_reasons",
  // 	label: "Disqualify Reasons",
  // 	value: { name: "DisqualificationReason", picklist_values: [] },
  // 	backendField: "disqualification_reason",
  // 	hovers: [],
  // 	isArray: false,
  // 	type: ["picklist"],
  // },
  // {
  // 	uid: "__variable1",
  // 	label: "Variable 1",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 0,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable2",
  // 	label: "Variable 2",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 1,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable3",
  // 	label: "Variable 3",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 2,
  // 	type: ["string"],
  // },
  // {
  // 	uid: "__variable4",
  // 	label: "Variable 4",
  // 	value: { name: "", label: "" },
  // 	backendField: "variables",
  // 	hovers: [],
  // 	isArray: true,
  // 	index: 3,
  // 	type: ["string"],
  // },
];

export const RINGOVER_FIELDS = {
  [VIEWS.LEAD]: LEAD_FIELDS,
  [VIEWS.CONTACT]: CONTACT_FIELDS,
  [VIEWS.ACCOUNT]: ACCOUNT_FIELDS,
};

export const DEFAULT_SF_FIELDS_STRUCT = {
  [VIEWS.LEAD]: [],
  [VIEWS.CONTACT]: [],
  [VIEWS.ACCOUNT]: [],
};

export const DEFAULT_TOPVIEW_DATA = {
  [VIEWS.LEAD]: 0,
  [VIEWS.CONTACT]: 0,
  [VIEWS.ACCOUNT]: 0,
};

export const CUSTOM_VARIABLES_HEADING = {
  [VIEWS.LEAD]: 20,
  [VIEWS.CONTACT]: 14,
  [VIEWS.ACCOUNT]: 7,
};

export const CUSTOM_FIELDS_HEADING = {
  [VIEWS.LEAD]: 19,
  [VIEWS.CONTACT]: 102,
  [VIEWS.ACCOUNT]: 6,
};

export const DEFAULT_VALUES = {
  [VIEWS.LEAD]: {
    __first_name: 'First_Name',
    __last_name: 'Last_Name',
    __job_position: 'Designation',
    __lead_company_name: 'Company',
    __company_url: 'Website',
    __zipcode: 'Zip_Code',
    __country: 'Country',
    __p_phone_number: 'Phone',
    __a_phone_number1: 'Other_Phone',
    __p_email: 'Email',
  },
  [VIEWS.ACCOUNT]: {
    __company_name: 'Account_Name',
    __company_phone_number: 'Phone',
    __company_url: 'Website',
    __zipcode: 'Shipping_Code',
    __country: 'Shipping_Country',
  },
  [VIEWS.CONTACT]: {
    __first_name: 'First_Name',
    __last_name: 'Last_Name',
    __job_position: 'Title',
    __p_phone_number: 'Phone',
    __p_email: 'Email',
  },
};
