export default {
  CALL: 'call',
  MESSAGE: 'message',
  MAIL: 'mail',
  MEETING: 'meeting',
  NOTE: 'note',
  AUTOMATED_MAIL: 'automated_mail',
  AUTOMATED_MESSAGE: 'automated_message',
  LINKEDIN_CONNECTION: 'linkedin_connection',
  LINKEDIN_MESSAGE: 'linkedin_message',
  LINKEDIN_PROFILE: 'linkedin_profile',
  LINKEDIN_INTERACT: 'linkedin_interact',
  PAUSE_CADENCE: 'pause_cadence',
  REPLY_TO: 'reply_to',
  RESUME_CADENCE: 'resume_cadence',
  STOP_CADENCE: 'stop_cadence',
  MOVE_CADENCE: 'move_cadence',
  LEAD_CONVERTED: 'lead_converted',
  LEAD_DISQUALIFIED: 'lead_disqualified',
  CONTACT_DISQUALIFIED: 'contact_disqualified',
  LAUNCH_CADENCE: 'launch_cadence',
  UNSUBSCRIBE: 'unsubscribe',
  TASK_SKIPPED: 'task_skipped',
  CLICKED_MAIL: 'clicked_mail',
  VIEWED_MAIL: 'viewed_mail',
  BOUNCED_MAIL: 'bounced_mail',
};
