export default {
  SALESFORCE_LEAD: 'salesforce_lead',
  SALESFORCE_CONTACT: 'salesforce_contact',
  SALESFORCE_GOOGLE_SHEET_LEAD: 'salesforce_google_sheet_lead',
  SALESFORCE_CSV_LEAD: 'salesforce_csv_lead',
  PIPEDRIVE_PERSON: 'pipedrive_person',
  HUBSPOT_CONTACT: 'hubspot_contact',
  SELLSY_CONTACT: 'sellsy_contact',
  GOOGLE_SHEETS_LEAD: 'google_sheets_lead',
  ZOHO_LEAD: 'zoho_lead',
  ZOHO_CONTACT: 'zoho_contact',
  EXCEL_LEAD: 'excel_lead',
  BULLHORN_LEAD: 'bullhorn_lead',
  BULLHORN_CONTACT: 'bullhorn_contact',
  BULLHORN_CANDIDATE: 'bullhorn_candidate',
  DYNAMICS_LEAD: 'dynamics_lead',
  DYNAMICS_CONTACT: 'dynamics_contact',
};
