import { INTEGRATION_TYPE } from '@cadence-support/constants';

export const CHANGE_LEAD_STATUS_DISABLED = [
  INTEGRATION_TYPE.GOOGLE_SHEETS,
  INTEGRATION_TYPE.EXCEL,
  INTEGRATION_TYPE.SELLSY,
  INTEGRATION_TYPE.DYNAMICS,
];

export const CHANGE_OWNER_DISABLED = [
  INTEGRATION_TYPE.GOOGLE_SHEETS,
  INTEGRATION_TYPE.EXCEL,
  INTEGRATION_TYPE.DYNAMICS,
];
